name: update

on:
  push:
  schedule:
    - cron: '0 10 * * 3'

jobs:
  update:
    name: update zonetab
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      run: sudo apt-get --no-install-recommends -q -y install ruby-dev gperf
    - name: Install dependencies
      run: sudo gem install --no-document nokogiri
    - name: Update zonetab
      working-directory: ext/date
      run: |
        make -f prereq.mk update-zonetab
        make -f prereq.mk zonetab.h
      env:
        top_srcdir: ../..
        srcdir: .
        RUBY: /usr/bin/ruby
    - name: Check diffs
      run: |
        git config --global user.email "nobu@ruby-lang.org"
        git config --global user.name "Nobuyoshi Nakada"
        git commit --allow-empty --message="Update zonetab.h at $(date +%F)" ext/date
        git diff --no-ext-diff --ignore-submodules --exit-code HEAD^..HEAD ||
        {
          git pull --ff-only origin ${GITHUB_REF#refs/heads/}
          git push origin ${GITHUB_REF#refs/heads/}
        }
